SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:superset@superset-db:5432/superset"

HTML_SANITIZATION = False
ENABLE_JAVASCRIPT_CONTROLS = True
ALLOW_JAVASCRIPT_IN_MARKDOWN = True

FEATURE_FLAGS = {
    "ENABLE_ECHARTS": True,
    "ENABLE_TIME_SERIES": True,
    "NEW_CHARTS": True,
    "NEW_EXPLORE_EXPERIENCE": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "ALLOW_JAVASCRIPT_XSS": True,
}
